add_header Strict-Transport-Security 'max-age=31536000; includeSubDomains; preload';
# add_header Content-Security-Policy "img-src 'self' data:; default-src 'self' https: 'unsafe-eval' 'unsafe-inline';";
# add_header X-Frame-Options "SAMEORIGIN";
# add_header X-Content-Type-Options nosniff;