import logging
import os
from harticle.utils import constants
from utils.data_kube_job_agent import EnvVariables
from utils.data_kube_job_agent import read_all_and_invoke
from utils.data_kube_job_client import DataKubeJobClient
from flask import Flask
from flask import request

LOGGER = logging.getLogger(__name__)

# x = torch.rand(5, 3)
# print(x)

cuda_available = "no"
# if torch.cuda.is_available():
#     cuda_available = "yes"
print("cuda is available: " + cuda_available)
app = Flask(__name__)


def _create_article_stub(env_vars: EnvVariables, data_kube_client: DataKubeJobClient):
    """Fast local-dev path: publish Kafka progress/metadata without loading ML models."""
    LOGGER.info("Stub article generation for ID: %s", env_vars.article_id)
    keywords = env_vars.article_keywords or "harticle dev"
    # Placeholder image so sport6/yalla cards are readable (empty image => white bg + light text).
    image_seed = abs(hash(keywords)) % 10000
    stub_image = f'https://picsum.photos/seed/harticle-{image_seed}/800/500'
    data_kube_client.send_metadata({'progress': '50'})
    data_kube_client.send_metadata({
        'title': f'[dev] {keywords}',
        'sub_title': 'Generated by Harticle engine stub',
        'content': f'Stub article body for keywords: {keywords}',
        'image': stub_image,
    })
    data_kube_client.send_metadata({'progress': '100'})
    data_kube_client.send_job_status(status=data_kube_client.Status.SUCCESS)


def create_article(env_vars: EnvVariables, data_kube_client: DataKubeJobClient):
    if os.getenv("HARTICLE_ENGINE_STUB", "").strip() == "1":
        _create_article_stub(env_vars, data_kube_client)
        return

    LOGGER.info("Creating article content for ID: " + env_vars.article_id)

    from transformers import AutoTokenizer, AutoModelForCausalLM
    import numpy as np
    import torch
    from serper_google_images import get_google_image

    LOGGER.info("Sending SUBTASK_COMPLETED")
    data_kube_client.send_subtask_completed(status=data_kube_client.Status.SUCCESS)

    # Which model to run for inference. Defaults to the original fine-tune, but a
    # custom model produced by the training agent can be selected by setting
    # HARTICLE_INFERENCE_MODEL to its HF Hub repo id (or a local dir downloaded
    # from object storage). This is how a freshly trained model goes live.
    inference_model = os.getenv("HARTICLE_INFERENCE_MODEL", "devozs/hebrew-gpt_neo-small-soccer-news")
    LOGGER.info("loading inference model: %s", inference_model)
    tokenizer = AutoTokenizer.from_pretrained(inference_model)
    model = AutoModelForCausalLM.from_pretrained(inference_model,
                                                 pad_token_id=tokenizer.eos_token_id)

    prompt_text = "מכבי חיפה שוב מנצחת אחרי שער בדקות הסיום"
    prompt_text = env_vars.article_keywords
    temp = int(env_vars.temperature) / 100
    if temp < 0.1:
        temp = 0.5
    print("temperature:", temp)

    image = get_google_image(prompt_text)
    print("image:", image)

    # max_len = 256
    max_len = 512
    sample_output_num = 3
    seed = 1000
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    n_gpu = 0 if torch.cuda.is_available() == False else torch.cuda.device_count()
    print(f"device: {device}, n_gpu: {n_gpu}")

    np.random.seed(seed)
    torch.manual_seed(seed)
    if n_gpu > 0:
        torch.cuda.manual_seed_all(seed)

    model.to(device)
    encoded_prompt = tokenizer.encode(
        prompt_text, add_special_tokens=False, return_tensors="pt")
    encoded_prompt = encoded_prompt.to(device)

    if encoded_prompt.size()[-1] == 0:
        input_ids = None
    else:
        input_ids = encoded_prompt
    print("input_ids = " + str(input_ids))

    if input_ids is not None:
        max_len += len(encoded_prompt[0])
        if max_len > 2048:
            max_len = 2048

    print("Updated max_len = " + str(max_len))

    stop_token = "<|endoftext|>"
    new_lines = "\
    \
    \
    "

    sample_outputs = model.generate(
        input_ids,
        do_sample=True,
        max_length=max_len,
        # top_k=50,  # number of words to select in the context of the last word
        # top_p=0.95,  # the chance the select next word in regard to the prev words
        temperature=temp,  # the chance to generate whole text as close to reality or not. lower means closer to reality
        num_return_sequences=sample_output_num
    )
    LOGGER.info("Sending ADD_METADATA_MESSAGE")
    data_kube_client.send_metadata({'progress': '50'})

    print(100 * '-' + "\
    \t\tOutput\
    " + 100 * '-')
    for i, sample_output in enumerate(sample_outputs):
        text = tokenizer.decode(sample_output, skip_special_tokens=True)
        # Remove all text after the stop token
        text = text[: text.find(stop_token) if stop_token else None]
        # Remove all text after 3 newlines
        text = text[: text.find(new_lines) if new_lines else None]

        print("{}: {} ({})".format(i, text, len(text)))
        print("" + 100 * '-')
        if i == 0:
            print("Sending ADD_METADATA_MESSAGE")
            title = ""
            sub_title = ""
            content = ""

            full_text = text.split(".")
            if full_text is not None and len(full_text) > 2:
                title = text.split(".")[0]
                sub_title = text.split(".")[1]
                for j in range(len(full_text)):
                    if j == 0 or j == 1:
                        continue
                    content += full_text[j] + "\n"
            print("title: {} ({})".format(title, len(title)))
            print("sub_title: {} ({})".format(sub_title, len(sub_title)))
            print("content: {} ({})".format(content, len(content)))
            print("image: {} ({})".format(content, len(image)))
            data_kube_client.send_metadata({
                'title': '{}'.format(title),
                'sub_title': '{}'.format(sub_title),
                'content': '{}'.format(content),
                'image': '{}'.format(image),
            })

    print("Sending ADD_METADATA_MESSAGE")
    data_kube_client.send_metadata({'progress': '100'})

    print("Sending FINISH_JOB")
    data_kube_client.send_job_status(status=data_kube_client.Status.SUCCESS)

    # sleep(30)
    LOGGER.info("End of create_article")


@app.route('/engine', methods=['GET'])
def hello():
    return "Hello Flask"


@app.route('/engine/infer', methods=['POST'])
def infer():
    """Synchronous inference test, decoupled from the Kafka/article flow.

    Loads a trained model (HF Hub repo id, or downloads from storage) and runs the
    prompt through it on CPU (or GPU if present). Called by management for the
    "Local (CPU, this deployment)" inference target. INTERNAL ONLY — never expose
    on a public ingress (it loads arbitrary model refs).
    """
    from harticle import inference

    body = request.get_json(force=True) or {}
    model_ref = body.get("modelRef")
    if not model_ref:
        return {"error": "modelRef is required"}, 400
    params = {
        "temperature": body.get("temperature"),
        "maxLength": body.get("maxLength"),
        "numReturnSequences": body.get("numReturnSequences"),
    }
    try:
        outputs = inference.run_inference(
            model_ref,
            body.get("prompt") or "",
            params,
            storage_kind=body.get("storageKind"),
            model_key_prefix=body.get("modelKeyPrefix"),
        )
        device = "stub" if os.getenv("HARTICLE_ENGINE_STUB", "").strip() == "1" else None
        if device is None:
            import torch
            device = "cuda" if torch.cuda.is_available() else "cpu"
        return {"outputs": outputs, "device": device, "model": model_ref, "error": None}, 200
    except Exception as e:
        LOGGER.exception("inference failed for model %s", model_ref)
        return {"outputs": None, "device": None, "model": model_ref, "error": str(e)}, 500


@app.route('/engine/generate', methods=['POST'])
def generate():
    if request.method == 'POST':
        content_type = request.headers.get('Content-Type')
        if (content_type == 'application/json'):
            json = request.json
            tenant_id = json['tenant_id']
            security_identifier = json['security_identifier']
            data_kube_job_id = json['data_kube_job_id']
            kube_job_id = json['kube_job_id']
            user_name = json['user_name']
            kafka_password = json['kafka_password']
            user_email = json['user_email']
            article_id = json['article_id']
            env_name = json['env_name']
            article_keywords = json['article_keywords']
            reporter_id = json['reporter_id']
            reporter_name = json['reporter_name']
            temperature = json.get('temperature', 50)
            env_vars: EnvVariables = EnvVariables(
                tenant_id,
                security_identifier,
                data_kube_job_id,
                kube_job_id,
                user_name,
                kafka_password,
                user_email,
                article_id,
                env_name,
                article_keywords,
                reporter_id,
                reporter_name,
                str(temperature))
            read_all_and_invoke(create_article, env_vars)
            return "New article create for keywords: " + article_keywords, 200


if __name__ == "__main__":
    data_kube_job_id = os.getenv(constants.ENV_DATA_KUBE_JOB_ID)
    if data_kube_job_id is None:
        LOGGER.info("Running as Pod (Flask")
        port = int(os.getenv("PORT", "5000"))
        debug = os.getenv("FLASK_DEBUG", "0") == "1"
        app.run(debug=debug, host="0.0.0.0", port=port, use_reloader=False)
    else:
        LOGGER.info("Running as Job")
        read_all_and_invoke(create_article)
