# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infrastructuresettings.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cinfrastructuresettings.proto\x12\x08\x64\x61takube\"W\n\x15KafkaConfigurationDto\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05topic\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\x12\x10\n\x08password\x18\x04 \x01(\tBX\n8com.devozs.components.common.dto.infrastructure.settingsB\x1cInfrastructureSettingsProtosb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'infrastructuresettings_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n8com.devozs.components.common.dto.infrastructure.settingsB\034InfrastructureSettingsProtos'
  _KAFKACONFIGURATIONDTO._serialized_start=42
  _KAFKACONFIGURATIONDTO._serialized_end=129
# @@protoc_insertion_point(module_scope)
