JOBS_ROOT_FOLDER = 'jobs'
CONFIG_FILE_BASE_PATH = '/etc/config'
CONFIG_FILE_DATASOURCE_PATH = '/etc/datasource/config'

JSON_CONFIG_SUFFIX = ".json"
DATA_SUFFIX = ".data"
PROTO_CONFIG_SUFFIX = ".config"

BASE_CONFIG_FILE_NAME_CACHE_STORAGE = 'cache_storage'
BASE_CONFIG_FILE_NAME_ARTIFACT_STORAGE = 'artifact_storage'
BASE_CONFIG_FILE_NAME_EXTERNAL_ARTIFACT_STORAGE = 'external_artifact_storage'
BASE_CONFIG_FILE_NAME_AZURE_GATEWAY = 'azure_gateway'
BASE_CONFIG_FILE_NAME_KAFKA_CONFIG = 'kafka_config'
BASE_CONFIG_FILE_NAME_SPARK_CONFIG = 'spark_config'
BASE_CONFIG_FILE_NAME_ORIGIN_DS_CONFIG = "origin_data_source"
BASE_CONFIG_FILE_NAME_TARGET_DS_CONFIG = "target_data_source"
BASE_CONFIG_FILE_NAME_ADDITIONAL_JOB_CONFIG = "job_additional_config"
BASE_CONFIG_FILE_NAME_SCHEMA_DISCOVERY = 'schema_discovery'
BASE_CONFIG_FILE_NAME_VALIDATION = 'validation'

ENV_VARIABLE_TENANT_ID = 'TENANT_ID'
ENV_VARIABLE_USER_NAME = 'USER_NAME'
ENV_VARIABLE_KAFKA_PASSWORD = 'KAFKA_PASSWORD'
ENV_VARIABLE_USER_EMAIL = 'USER_EMAIL'
ENV_VARIABLE_ENV_NAME = 'ENV_NAME'
ENV_VARIABLE_ARTICLE_ID = 'ARTICLE_ID'
ENV_VARIABLE_ARTICLE_KEYWORDS = "ARTICLE_KEYWORDS"
ENV_VARIABLE_REPORTER_ID = 'REPORTER_ID'
ENV_VARIABLE_REPORTER_NAME = 'REPORTER_NAME'
ENV_VARIABLE_TEMPERATURE = 'TEMPERATURE'
ENV_SECURITY_IDENTIFIER = 'SECURITY_IDENTIFIER'
ENV_DATA_KUBE_JOB_ID = 'DATA_KUBE_JOB_ID'
ENV_KUBE_JOB_ID = 'KUBE_JOB_ID'
ENV_DEBUG_PORT = 'DEBUG_PORT'
ENV_DEBUG_PORT_PYCHARM = 'DEBUG_PORT_PYCHARM'
ENV_DEBUG_WAIT_FOR_CLIENT = 'DEBUG_WAIT_FOR_CLIENT'

ARCH_TYPE_CPU = 'cpu'
ARCH_TYPE_GPU = 'gpu'

# Automation paths
CONFIGURATION_PATH_FOLDER = './config_files/general'
DATA_SOURCE_CONFIGURATION_PATH_FOLDER = './config_files/data_source'
EXPECTED_RESULTS_BUCKET = 'test-expected-results'
DATASOURCE_BUCKET = "datasources"
FLOWS_FOLDER = "flows"
